---
title: "Laporan Analisis Varians (ANOVA)"
output: pdf_document
params:
  test_type: NULL
  inputs: NULL
  asumsi_status: NULL
  anova_result: NULL
  posthoc_result: NULL
  interpretation: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

## Hasil Analisis: `r params$test_type`

- Variabel Dependen: `r params$inputs$dv`
- Variabel Independen: `r if(params$test_type == "ANOVA 1 Arah") params$inputs$iv else paste(params$inputs$iv1, "dan", params$inputs$iv2)`

## Pemeriksaan Asumsi
Status pemeriksaan asumsi (Normalitas & Homogenitas): `r params$asumsi_status`

```{r}
if(!is.null(params$anova_result)){
  knitr::kable(params$anova_result[[1]], caption = "Tabel Ringkasan ANOVA")
} else {
  cat("Analisis ANOVA tidak dijalankan.")
}
```

```{r}
if(!is.null(params$posthoc_result)){
  knitr::kable(params$posthoc_result[[1]], caption = "Hasil Uji Lanjutan Tukey HSD")
} else {
  cat("Uji lanjut tidak dilakukan.")
}
```

```{r interpretation-text, results='asis'}
if(!is.null(params$interpretation)){

  clean_interpretation <- gsub("<ul>|</ul>|<li>|</li>|</p>", "", params$interpretation)
  clean_interpretation <- gsub("<p>", "\n", clean_interpretation)
  clean_interpretation <- gsub("<b>|</b>", "**", clean_interpretation)
  
  cat(clean_interpretation)
}
```

